// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::liquidity_pool_type::LiquidityPool;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `liquidity_pools`.
///
/// Obtain a handle from the [`LiquidityPoolsTableAccess::liquidity_pools`] method on [`super::RemoteTables`],
/// like `ctx.db.liquidity_pools()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.liquidity_pools().on_insert(...)`.
pub struct LiquidityPoolsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiquidityPool>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `liquidity_pools`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiquidityPoolsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiquidityPoolsTableHandle`], which mediates access to the table `liquidity_pools`.
    fn liquidity_pools(&self) -> LiquidityPoolsTableHandle<'_>;
}

impl LiquidityPoolsTableAccess for super::RemoteTables {
    fn liquidity_pools(&self) -> LiquidityPoolsTableHandle<'_> {
        LiquidityPoolsTableHandle {
            imp: self.imp.get_table::<LiquidityPool>("liquidity_pools"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiquidityPoolsInsertCallbackId(__sdk::CallbackId);
pub struct LiquidityPoolsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiquidityPoolsTableHandle<'ctx> {
    type Row = LiquidityPool;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiquidityPool> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiquidityPoolsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiquidityPoolsInsertCallbackId {
        LiquidityPoolsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiquidityPoolsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiquidityPoolsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiquidityPoolsDeleteCallbackId {
        LiquidityPoolsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiquidityPoolsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiquidityPool>("liquidity_pools");
    _table.add_unique_constraint::<String>("principal", |row| &row.principal);
}
pub struct LiquidityPoolsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiquidityPoolsTableHandle<'ctx> {
    type UpdateCallbackId = LiquidityPoolsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiquidityPoolsUpdateCallbackId {
        LiquidityPoolsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiquidityPoolsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<LiquidityPool>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiquidityPool>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `principal` unique index on the table `liquidity_pools`,
/// which allows point queries on the field of the same name
/// via the [`LiquidityPoolsPrincipalUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.liquidity_pools().principal().find(...)`.
pub struct LiquidityPoolsPrincipalUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiquidityPool, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiquidityPoolsTableHandle<'ctx> {
    /// Get a handle on the `principal` unique index on the table `liquidity_pools`.
    pub fn principal(&self) -> LiquidityPoolsPrincipalUnique<'ctx> {
        LiquidityPoolsPrincipalUnique {
            imp: self.imp.get_unique_constraint::<String>("principal"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiquidityPoolsPrincipalUnique<'ctx> {
    /// Find the subscribed row whose `principal` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LiquidityPool> {
        self.imp.find(col_val)
    }
}
