// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterNewUserArgs {
    pub principal: String,
}

impl From<RegisterNewUserArgs> for super::Reducer {
    fn from(args: RegisterNewUserArgs) -> Self {
        Self::RegisterNewUser {
            principal: args.principal,
        }
    }
}

impl __sdk::InModule for RegisterNewUserArgs {
    type Module = super::RemoteModule;
}

pub struct RegisterNewUserCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_new_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_new_user {
    /// Request that the remote module invoke the reducer `register_new_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_register_new_user`] callbacks.
    fn register_new_user(&self, principal: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_new_user`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RegisterNewUserCallbackId`] can be passed to [`Self::remove_on_register_new_user`]
    /// to cancel the callback.
    fn on_register_new_user(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RegisterNewUserCallbackId;
    /// Cancel a callback previously registered by [`Self::on_register_new_user`],
    /// causing it not to run in the future.
    fn remove_on_register_new_user(&self, callback: RegisterNewUserCallbackId);
}

impl register_new_user for super::RemoteReducers {
    fn register_new_user(&self, principal: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("register_new_user", RegisterNewUserArgs { principal })
    }
    fn on_register_new_user(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> RegisterNewUserCallbackId {
        RegisterNewUserCallbackId(self.imp.on_reducer(
            "register_new_user",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RegisterNewUser { principal },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, principal)
            }),
        ))
    }
    fn remove_on_register_new_user(&self, callback: RegisterNewUserCallbackId) {
        self.imp.remove_on_reducer("register_new_user", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `register_new_user`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_register_new_user {
    /// Set the call-reducer flags for the reducer `register_new_user` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn register_new_user(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_new_user for super::SetReducerFlags {
    fn register_new_user(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("register_new_user", flags);
    }
}
