// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::reset_withdrawal_schedule_type::ResetWithdrawalSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ResetWithdrawalAmtArgs {
    pub arg: ResetWithdrawalSchedule,
}

impl From<ResetWithdrawalAmtArgs> for super::Reducer {
    fn from(args: ResetWithdrawalAmtArgs) -> Self {
        Self::ResetWithdrawalAmt { arg: args.arg }
    }
}

impl __sdk::InModule for ResetWithdrawalAmtArgs {
    type Module = super::RemoteModule;
}

pub struct ResetWithdrawalAmtCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reset_withdrawal_amt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reset_withdrawal_amt {
    /// Request that the remote module invoke the reducer `reset_withdrawal_amt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_reset_withdrawal_amt`] callbacks.
    fn reset_withdrawal_amt(&self, arg: ResetWithdrawalSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `reset_withdrawal_amt`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ResetWithdrawalAmtCallbackId`] can be passed to [`Self::remove_on_reset_withdrawal_amt`]
    /// to cancel the callback.
    fn on_reset_withdrawal_amt(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &ResetWithdrawalSchedule) + Send + 'static,
    ) -> ResetWithdrawalAmtCallbackId;
    /// Cancel a callback previously registered by [`Self::on_reset_withdrawal_amt`],
    /// causing it not to run in the future.
    fn remove_on_reset_withdrawal_amt(&self, callback: ResetWithdrawalAmtCallbackId);
}

impl reset_withdrawal_amt for super::RemoteReducers {
    fn reset_withdrawal_amt(&self, arg: ResetWithdrawalSchedule) -> __sdk::Result<()> {
        self.imp
            .call_reducer("reset_withdrawal_amt", ResetWithdrawalAmtArgs { arg })
    }
    fn on_reset_withdrawal_amt(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &ResetWithdrawalSchedule) + Send + 'static,
    ) -> ResetWithdrawalAmtCallbackId {
        ResetWithdrawalAmtCallbackId(self.imp.on_reducer(
            "reset_withdrawal_amt",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ResetWithdrawalAmt { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_reset_withdrawal_amt(&self, callback: ResetWithdrawalAmtCallbackId) {
        self.imp
            .remove_on_reducer("reset_withdrawal_amt", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `reset_withdrawal_amt`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_reset_withdrawal_amt {
    /// Set the call-reducer flags for the reducer `reset_withdrawal_amt` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn reset_withdrawal_amt(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_reset_withdrawal_amt for super::SetReducerFlags {
    fn reset_withdrawal_amt(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("reset_withdrawal_amt", flags);
    }
}
