// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::reset_withdrawal_schedule_type::ResetWithdrawalSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `reset_withdrawal_schedule`.
///
/// Obtain a handle from the [`ResetWithdrawalScheduleTableAccess::reset_withdrawal_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.reset_withdrawal_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.reset_withdrawal_schedule().on_insert(...)`.
pub struct ResetWithdrawalScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResetWithdrawalSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `reset_withdrawal_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResetWithdrawalScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResetWithdrawalScheduleTableHandle`], which mediates access to the table `reset_withdrawal_schedule`.
    fn reset_withdrawal_schedule(&self) -> ResetWithdrawalScheduleTableHandle<'_>;
}

impl ResetWithdrawalScheduleTableAccess for super::RemoteTables {
    fn reset_withdrawal_schedule(&self) -> ResetWithdrawalScheduleTableHandle<'_> {
        ResetWithdrawalScheduleTableHandle {
            imp: self
                .imp
                .get_table::<ResetWithdrawalSchedule>("reset_withdrawal_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResetWithdrawalScheduleInsertCallbackId(__sdk::CallbackId);
pub struct ResetWithdrawalScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResetWithdrawalScheduleTableHandle<'ctx> {
    type Row = ResetWithdrawalSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResetWithdrawalSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResetWithdrawalScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResetWithdrawalScheduleInsertCallbackId {
        ResetWithdrawalScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResetWithdrawalScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResetWithdrawalScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResetWithdrawalScheduleDeleteCallbackId {
        ResetWithdrawalScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResetWithdrawalScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<ResetWithdrawalSchedule>("reset_withdrawal_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ResetWithdrawalScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResetWithdrawalScheduleTableHandle<'ctx> {
    type UpdateCallbackId = ResetWithdrawalScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResetWithdrawalScheduleUpdateCallbackId {
        ResetWithdrawalScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResetWithdrawalScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ResetWithdrawalSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResetWithdrawalSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `reset_withdrawal_schedule`,
/// which allows point queries on the field of the same name
/// via the [`ResetWithdrawalScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.reset_withdrawal_schedule().scheduled_id().find(...)`.
pub struct ResetWithdrawalScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResetWithdrawalSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResetWithdrawalScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `reset_withdrawal_schedule`.
    pub fn scheduled_id(&self) -> ResetWithdrawalScheduleScheduledIdUnique<'ctx> {
        ResetWithdrawalScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResetWithdrawalScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ResetWithdrawalSchedule> {
        self.imp.find(col_val)
    }
}
