// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::notification_type_type::NotificationType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddNotificationArgs {
    pub principal: String,
    pub payload: NotificationType,
}

impl From<AddNotificationArgs> for super::Reducer {
    fn from(args: AddNotificationArgs) -> Self {
        Self::AddNotification {
            principal: args.principal,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for AddNotificationArgs {
    type Module = super::RemoteModule;
}

pub struct AddNotificationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_notification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_notification {
    /// Request that the remote module invoke the reducer `add_notification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_notification`] callbacks.
    fn add_notification(&self, principal: String, payload: NotificationType) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_notification`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddNotificationCallbackId`] can be passed to [`Self::remove_on_add_notification`]
    /// to cancel the callback.
    fn on_add_notification(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &NotificationType) + Send + 'static,
    ) -> AddNotificationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_notification`],
    /// causing it not to run in the future.
    fn remove_on_add_notification(&self, callback: AddNotificationCallbackId);
}

impl add_notification for super::RemoteReducers {
    fn add_notification(&self, principal: String, payload: NotificationType) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_notification",
            AddNotificationArgs { principal, payload },
        )
    }
    fn on_add_notification(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &NotificationType)
            + Send
            + 'static,
    ) -> AddNotificationCallbackId {
        AddNotificationCallbackId(self.imp.on_reducer(
            "add_notification",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddNotification { principal, payload },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, principal, payload)
            }),
        ))
    }
    fn remove_on_add_notification(&self, callback: AddNotificationCallbackId) {
        self.imp.remove_on_reducer("add_notification", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_notification`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_notification {
    /// Set the call-reducer flags for the reducer `add_notification` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_notification(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_notification for super::SetReducerFlags {
    fn add_notification(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_notification", flags);
    }
}
