// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DolrAirdropInfo {
    pub user_principal: String,
    pub airdrop_count_within_duration: u64,
    pub last_airdrop_at: __sdk::Timestamp,
}

impl __sdk::InModule for DolrAirdropInfo {
    type Module = super::RemoteModule;
}
