// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::dolr_airdrop_info_type::DolrAirdropInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dolr_airdrop_info`.
///
/// Obtain a handle from the [`DolrAirdropInfoTableAccess::dolr_airdrop_info`] method on [`super::RemoteTables`],
/// like `ctx.db.dolr_airdrop_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dolr_airdrop_info().on_insert(...)`.
pub struct DolrAirdropInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<DolrAirdropInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dolr_airdrop_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DolrAirdropInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DolrAirdropInfoTableHandle`], which mediates access to the table `dolr_airdrop_info`.
    fn dolr_airdrop_info(&self) -> DolrAirdropInfoTableHandle<'_>;
}

impl DolrAirdropInfoTableAccess for super::RemoteTables {
    fn dolr_airdrop_info(&self) -> DolrAirdropInfoTableHandle<'_> {
        DolrAirdropInfoTableHandle {
            imp: self.imp.get_table::<DolrAirdropInfo>("dolr_airdrop_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DolrAirdropInfoInsertCallbackId(__sdk::CallbackId);
pub struct DolrAirdropInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DolrAirdropInfoTableHandle<'ctx> {
    type Row = DolrAirdropInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DolrAirdropInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DolrAirdropInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DolrAirdropInfoInsertCallbackId {
        DolrAirdropInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DolrAirdropInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DolrAirdropInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DolrAirdropInfoDeleteCallbackId {
        DolrAirdropInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DolrAirdropInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DolrAirdropInfo>("dolr_airdrop_info");
    _table.add_unique_constraint::<String>("user_principal", |row| &row.user_principal);
}
pub struct DolrAirdropInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DolrAirdropInfoTableHandle<'ctx> {
    type UpdateCallbackId = DolrAirdropInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DolrAirdropInfoUpdateCallbackId {
        DolrAirdropInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DolrAirdropInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DolrAirdropInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DolrAirdropInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_principal` unique index on the table `dolr_airdrop_info`,
/// which allows point queries on the field of the same name
/// via the [`DolrAirdropInfoUserPrincipalUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dolr_airdrop_info().user_principal().find(...)`.
pub struct DolrAirdropInfoUserPrincipalUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DolrAirdropInfo, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DolrAirdropInfoTableHandle<'ctx> {
    /// Get a handle on the `user_principal` unique index on the table `dolr_airdrop_info`.
    pub fn user_principal(&self) -> DolrAirdropInfoUserPrincipalUnique<'ctx> {
        DolrAirdropInfoUserPrincipalUnique {
            imp: self.imp.get_unique_constraint::<String>("user_principal"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DolrAirdropInfoUserPrincipalUnique<'ctx> {
    /// Find the subscribed row whose `user_principal` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<DolrAirdropInfo> {
        self.imp.find(col_val)
    }
}
