// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::notification_data_type::NotificationData;
use super::notification_type::Notification;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `notification`.
///
/// Obtain a handle from the [`NotificationTableAccess::notification`] method on [`super::RemoteTables`],
/// like `ctx.db.notification()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notification().on_insert(...)`.
pub struct NotificationTableHandle<'ctx> {
    imp: __sdk::TableHandle<Notification>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `notification`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NotificationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NotificationTableHandle`], which mediates access to the table `notification`.
    fn notification(&self) -> NotificationTableHandle<'_>;
}

impl NotificationTableAccess for super::RemoteTables {
    fn notification(&self) -> NotificationTableHandle<'_> {
        NotificationTableHandle {
            imp: self.imp.get_table::<Notification>("notification"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NotificationInsertCallbackId(__sdk::CallbackId);
pub struct NotificationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NotificationTableHandle<'ctx> {
    type Row = Notification;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Notification> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NotificationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationInsertCallbackId {
        NotificationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NotificationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NotificationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationDeleteCallbackId {
        NotificationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NotificationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Notification>("notification");
    _table.add_unique_constraint::<__sdk::Identity>("user", |row| &row.user);
}
pub struct NotificationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NotificationTableHandle<'ctx> {
    type UpdateCallbackId = NotificationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NotificationUpdateCallbackId {
        NotificationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NotificationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Notification>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Notification>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user` unique index on the table `notification`,
/// which allows point queries on the field of the same name
/// via the [`NotificationUserUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notification().user().find(...)`.
pub struct NotificationUserUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Notification, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NotificationTableHandle<'ctx> {
    /// Get a handle on the `user` unique index on the table `notification`.
    pub fn user(&self) -> NotificationUserUnique<'ctx> {
        NotificationUserUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("user"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NotificationUserUnique<'ctx> {
    /// Find the subscribed row whose `user` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Notification> {
        self.imp.find(col_val)
    }
}
