// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::notification_type::Notification;
use super::notifications_type::Notifications;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `notifications`.
///
/// Obtain a handle from the [`NotificationsTableAccess::notifications`] method on [`super::RemoteTables`],
/// like `ctx.db.notifications()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notifications().on_insert(...)`.
pub struct NotificationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Notification>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `notifications`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NotificationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NotificationsTableHandle`], which mediates access to the table `notifications`.
    fn notifications(&self) -> NotificationsTableHandle<'_>;
}

impl NotificationsTableAccess for super::RemoteTables {
    fn notifications(&self) -> NotificationsTableHandle<'_> {
        NotificationsTableHandle {
            imp: self.imp.get_table::<Notification>("notifications"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NotificationsInsertCallbackId(__sdk::CallbackId);
pub struct NotificationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NotificationsTableHandle<'ctx> {
    type Row = Notification;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Notification> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NotificationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationsInsertCallbackId {
        NotificationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NotificationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NotificationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationsDeleteCallbackId {
        NotificationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NotificationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Notification>("notifications");
    _table.add_unique_constraint::<__sdk::Identity>("user", |row| &row.user);
}
pub struct NotificationsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NotificationsTableHandle<'ctx> {
    type UpdateCallbackId = NotificationsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NotificationsUpdateCallbackId {
        NotificationsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NotificationsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Notification>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Notification>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user` unique index on the table `notifications`,
/// which allows point queries on the field of the same name
/// via the [`NotificationsUserUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notifications().user().find(...)`.
pub struct NotificationsUserUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Notification, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NotificationsTableHandle<'ctx> {
    /// Get a handle on the `user` unique index on the table `notifications`.
    pub fn user(&self) -> NotificationsUserUnique<'ctx> {
        NotificationsUserUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("user"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NotificationsUserUnique<'ctx> {
    /// Find the subscribed row whose `user` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Notification> {
        self.imp.find(col_val)
    }
}
