// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::notification_prune_schedule_type::NotificationPruneSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `notification_prune_schedule`.
///
/// Obtain a handle from the [`NotificationPruneScheduleTableAccess::notification_prune_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.notification_prune_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notification_prune_schedule().on_insert(...)`.
pub struct NotificationPruneScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<NotificationPruneSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `notification_prune_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NotificationPruneScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NotificationPruneScheduleTableHandle`], which mediates access to the table `notification_prune_schedule`.
    fn notification_prune_schedule(&self) -> NotificationPruneScheduleTableHandle<'_>;
}

impl NotificationPruneScheduleTableAccess for super::RemoteTables {
    fn notification_prune_schedule(&self) -> NotificationPruneScheduleTableHandle<'_> {
        NotificationPruneScheduleTableHandle {
            imp: self
                .imp
                .get_table::<NotificationPruneSchedule>("notification_prune_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NotificationPruneScheduleInsertCallbackId(__sdk::CallbackId);
pub struct NotificationPruneScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NotificationPruneScheduleTableHandle<'ctx> {
    type Row = NotificationPruneSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NotificationPruneSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NotificationPruneScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationPruneScheduleInsertCallbackId {
        NotificationPruneScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NotificationPruneScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NotificationPruneScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NotificationPruneScheduleDeleteCallbackId {
        NotificationPruneScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NotificationPruneScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<NotificationPruneSchedule>("notification_prune_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct NotificationPruneScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NotificationPruneScheduleTableHandle<'ctx> {
    type UpdateCallbackId = NotificationPruneScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NotificationPruneScheduleUpdateCallbackId {
        NotificationPruneScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NotificationPruneScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NotificationPruneSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NotificationPruneSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `notification_prune_schedule`,
/// which allows point queries on the field of the same name
/// via the [`NotificationPruneScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.notification_prune_schedule().scheduled_id().find(...)`.
pub struct NotificationPruneScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NotificationPruneSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NotificationPruneScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `notification_prune_schedule`.
    pub fn scheduled_id(&self) -> NotificationPruneScheduleScheduledIdUnique<'ctx> {
        NotificationPruneScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NotificationPruneScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NotificationPruneSchedule> {
        self.imp.find(col_val)
    }
}
