// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::sats_airdrop_info_type::SatsAirdropInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sats_airdrop_info`.
///
/// Obtain a handle from the [`SatsAirdropInfoTableAccess::sats_airdrop_info`] method on [`super::RemoteTables`],
/// like `ctx.db.sats_airdrop_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sats_airdrop_info().on_insert(...)`.
pub struct SatsAirdropInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<SatsAirdropInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sats_airdrop_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SatsAirdropInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SatsAirdropInfoTableHandle`], which mediates access to the table `sats_airdrop_info`.
    fn sats_airdrop_info(&self) -> SatsAirdropInfoTableHandle<'_>;
}

impl SatsAirdropInfoTableAccess for super::RemoteTables {
    fn sats_airdrop_info(&self) -> SatsAirdropInfoTableHandle<'_> {
        SatsAirdropInfoTableHandle {
            imp: self.imp.get_table::<SatsAirdropInfo>("sats_airdrop_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SatsAirdropInfoInsertCallbackId(__sdk::CallbackId);
pub struct SatsAirdropInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SatsAirdropInfoTableHandle<'ctx> {
    type Row = SatsAirdropInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SatsAirdropInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SatsAirdropInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SatsAirdropInfoInsertCallbackId {
        SatsAirdropInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SatsAirdropInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SatsAirdropInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SatsAirdropInfoDeleteCallbackId {
        SatsAirdropInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SatsAirdropInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SatsAirdropInfo>("sats_airdrop_info");
    _table.add_unique_constraint::<String>("user_principal", |row| &row.user_principal);
}
pub struct SatsAirdropInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SatsAirdropInfoTableHandle<'ctx> {
    type UpdateCallbackId = SatsAirdropInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SatsAirdropInfoUpdateCallbackId {
        SatsAirdropInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SatsAirdropInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SatsAirdropInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SatsAirdropInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_principal` unique index on the table `sats_airdrop_info`,
/// which allows point queries on the field of the same name
/// via the [`SatsAirdropInfoUserPrincipalUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sats_airdrop_info().user_principal().find(...)`.
pub struct SatsAirdropInfoUserPrincipalUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SatsAirdropInfo, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SatsAirdropInfoTableHandle<'ctx> {
    /// Get a handle on the `user_principal` unique index on the table `sats_airdrop_info`.
    pub fn user_principal(&self) -> SatsAirdropInfoUserPrincipalUnique<'ctx> {
        SatsAirdropInfoUserPrincipalUnique {
            imp: self.imp.get_unique_constraint::<String>("user_principal"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SatsAirdropInfoUserPrincipalUnique<'ctx> {
    /// Find the subscribed row whose `user_principal` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SatsAirdropInfo> {
        self.imp.find(col_val)
    }
}
