// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WithdrawalInfo {
    pub user: __sdk::Identity,
    pub withdrawal_amt_24_h: u128,
    pub last_reset_at: __sdk::Timestamp,
}

impl __sdk::InModule for WithdrawalInfo {
    type Module = super::RemoteModule;
}
