// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::withdrawal_info_type::WithdrawalInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `withdrawal_info`.
///
/// Obtain a handle from the [`WithdrawalInfoTableAccess::withdrawal_info`] method on [`super::RemoteTables`],
/// like `ctx.db.withdrawal_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.withdrawal_info().on_insert(...)`.
pub struct WithdrawalInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<WithdrawalInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `withdrawal_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WithdrawalInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WithdrawalInfoTableHandle`], which mediates access to the table `withdrawal_info`.
    fn withdrawal_info(&self) -> WithdrawalInfoTableHandle<'_>;
}

impl WithdrawalInfoTableAccess for super::RemoteTables {
    fn withdrawal_info(&self) -> WithdrawalInfoTableHandle<'_> {
        WithdrawalInfoTableHandle {
            imp: self.imp.get_table::<WithdrawalInfo>("withdrawal_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WithdrawalInfoInsertCallbackId(__sdk::CallbackId);
pub struct WithdrawalInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WithdrawalInfoTableHandle<'ctx> {
    type Row = WithdrawalInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WithdrawalInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WithdrawalInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WithdrawalInfoInsertCallbackId {
        WithdrawalInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WithdrawalInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WithdrawalInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WithdrawalInfoDeleteCallbackId {
        WithdrawalInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WithdrawalInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WithdrawalInfo>("withdrawal_info");
    _table.add_unique_constraint::<__sdk::Identity>("user", |row| &row.user);
}
pub struct WithdrawalInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WithdrawalInfoTableHandle<'ctx> {
    type UpdateCallbackId = WithdrawalInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WithdrawalInfoUpdateCallbackId {
        WithdrawalInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WithdrawalInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WithdrawalInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WithdrawalInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user` unique index on the table `withdrawal_info`,
/// which allows point queries on the field of the same name
/// via the [`WithdrawalInfoUserUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.withdrawal_info().user().find(...)`.
pub struct WithdrawalInfoUserUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WithdrawalInfo, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WithdrawalInfoTableHandle<'ctx> {
    /// Get a handle on the `user` unique index on the table `withdrawal_info`.
    pub fn user(&self) -> WithdrawalInfoUserUnique<'ctx> {
        WithdrawalInfoUserUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("user"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WithdrawalInfoUserUnique<'ctx> {
    /// Find the subscribed row whose `user` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<WithdrawalInfo> {
        self.imp.find(col_val)
    }
}
