// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddDeletedCanisterArgs {
    pub canister: String,
    pub user_id: String,
}

impl From<AddDeletedCanisterArgs> for super::Reducer {
    fn from(args: AddDeletedCanisterArgs) -> Self {
        Self::AddDeletedCanister {
            canister: args.canister,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for AddDeletedCanisterArgs {
    type Module = super::RemoteModule;
}

pub struct AddDeletedCanisterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_deleted_canister`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_deleted_canister {
    /// Request that the remote module invoke the reducer `add_deleted_canister` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_deleted_canister`] callbacks.
    fn add_deleted_canister(&self, canister: String, user_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_deleted_canister`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddDeletedCanisterCallbackId`] can be passed to [`Self::remove_on_add_deleted_canister`]
    /// to cancel the callback.
    fn on_add_deleted_canister(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AddDeletedCanisterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_deleted_canister`],
    /// causing it not to run in the future.
    fn remove_on_add_deleted_canister(&self, callback: AddDeletedCanisterCallbackId);
}

impl add_deleted_canister for super::RemoteReducers {
    fn add_deleted_canister(&self, canister: String, user_id: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_deleted_canister",
            AddDeletedCanisterArgs { canister, user_id },
        )
    }
    fn on_add_deleted_canister(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AddDeletedCanisterCallbackId {
        AddDeletedCanisterCallbackId(self.imp.on_reducer(
            "add_deleted_canister",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddDeletedCanister { canister, user_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, canister, user_id)
            }),
        ))
    }
    fn remove_on_add_deleted_canister(&self, callback: AddDeletedCanisterCallbackId) {
        self.imp
            .remove_on_reducer("add_deleted_canister", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_deleted_canister`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_deleted_canister {
    /// Set the call-reducer flags for the reducer `add_deleted_canister` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_deleted_canister(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_deleted_canister for super::SetReducerFlags {
    fn add_deleted_canister(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("add_deleted_canister", flags);
    }
}
