// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deleted_canisters_type::DeletedCanisters;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `deleted_canisters`.
///
/// Obtain a handle from the [`DeletedCanistersTableAccess::deleted_canisters`] method on [`super::RemoteTables`],
/// like `ctx.db.deleted_canisters()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deleted_canisters().on_insert(...)`.
pub struct DeletedCanistersTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeletedCanisters>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `deleted_canisters`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeletedCanistersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeletedCanistersTableHandle`], which mediates access to the table `deleted_canisters`.
    fn deleted_canisters(&self) -> DeletedCanistersTableHandle<'_>;
}

impl DeletedCanistersTableAccess for super::RemoteTables {
    fn deleted_canisters(&self) -> DeletedCanistersTableHandle<'_> {
        DeletedCanistersTableHandle {
            imp: self.imp.get_table::<DeletedCanisters>("deleted_canisters"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeletedCanistersInsertCallbackId(__sdk::CallbackId);
pub struct DeletedCanistersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeletedCanistersTableHandle<'ctx> {
    type Row = DeletedCanisters;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeletedCanisters> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeletedCanistersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeletedCanistersInsertCallbackId {
        DeletedCanistersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeletedCanistersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeletedCanistersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeletedCanistersDeleteCallbackId {
        DeletedCanistersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeletedCanistersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeletedCanisters>("deleted_canisters");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DeletedCanisters>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeletedCanisters>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
