[package]
name = "dedup_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spacetimedb = { workspace = true }
log = { workspace = true }
utils = { workspace = true }
