// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::video_hash_type::VideoHash;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dedup_index`.
///
/// Obtain a handle from the [`DedupIndexTableAccess::dedup_index`] method on [`super::RemoteTables`],
/// like `ctx.db.dedup_index()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dedup_index().on_insert(...)`.
pub struct DedupIndexTableHandle<'ctx> {
    imp: __sdk::TableHandle<VideoHash>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dedup_index`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DedupIndexTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DedupIndexTableHandle`], which mediates access to the table `dedup_index`.
    fn dedup_index(&self) -> DedupIndexTableHandle<'_>;
}

impl DedupIndexTableAccess for super::RemoteTables {
    fn dedup_index(&self) -> DedupIndexTableHandle<'_> {
        DedupIndexTableHandle {
            imp: self.imp.get_table::<VideoHash>("dedup_index"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DedupIndexInsertCallbackId(__sdk::CallbackId);
pub struct DedupIndexDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DedupIndexTableHandle<'ctx> {
    type Row = VideoHash;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VideoHash> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DedupIndexInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DedupIndexInsertCallbackId {
        DedupIndexInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DedupIndexInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DedupIndexDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DedupIndexDeleteCallbackId {
        DedupIndexDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DedupIndexDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VideoHash>("dedup_index");
    _table.add_unique_constraint::<String>("video_id", |row| &row.video_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VideoHash>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VideoHash>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `video_id` unique index on the table `dedup_index`,
/// which allows point queries on the field of the same name
/// via the [`DedupIndexVideoIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dedup_index().video_id().find(...)`.
pub struct DedupIndexVideoIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VideoHash, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DedupIndexTableHandle<'ctx> {
    /// Get a handle on the `video_id` unique index on the table `dedup_index`.
    pub fn video_id(&self) -> DedupIndexVideoIdUnique<'ctx> {
        DedupIndexVideoIdUnique {
            imp: self.imp.get_unique_constraint::<String>("video_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DedupIndexVideoIdUnique<'ctx> {
    /// Find the subscribed row whose `video_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<VideoHash> {
        self.imp.find(col_val)
    }
}
