// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::unique_hash_type::UniqueHash;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `unique_hash`.
///
/// Obtain a handle from the [`UniqueHashTableAccess::unique_hash`] method on [`super::RemoteTables`],
/// like `ctx.db.unique_hash()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unique_hash().on_insert(...)`.
pub struct UniqueHashTableHandle<'ctx> {
    imp: __sdk::TableHandle<UniqueHash>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `unique_hash`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UniqueHashTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UniqueHashTableHandle`], which mediates access to the table `unique_hash`.
    fn unique_hash(&self) -> UniqueHashTableHandle<'_>;
}

impl UniqueHashTableAccess for super::RemoteTables {
    fn unique_hash(&self) -> UniqueHashTableHandle<'_> {
        UniqueHashTableHandle {
            imp: self.imp.get_table::<UniqueHash>("unique_hash"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UniqueHashInsertCallbackId(__sdk::CallbackId);
pub struct UniqueHashDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UniqueHashTableHandle<'ctx> {
    type Row = UniqueHash;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UniqueHash> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UniqueHashInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UniqueHashInsertCallbackId {
        UniqueHashInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UniqueHashInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UniqueHashDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UniqueHashDeleteCallbackId {
        UniqueHashDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UniqueHashDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UniqueHash>("unique_hash");
    _table.add_unique_constraint::<String>("hash", |row| &row.hash);
}
pub struct UniqueHashUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UniqueHashTableHandle<'ctx> {
    type UpdateCallbackId = UniqueHashUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UniqueHashUpdateCallbackId {
        UniqueHashUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UniqueHashUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UniqueHash>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UniqueHash>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `hash` unique index on the table `unique_hash`,
/// which allows point queries on the field of the same name
/// via the [`UniqueHashHashUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unique_hash().hash().find(...)`.
pub struct UniqueHashHashUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UniqueHash, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UniqueHashTableHandle<'ctx> {
    /// Get a handle on the `hash` unique index on the table `unique_hash`.
    pub fn hash(&self) -> UniqueHashHashUnique<'ctx> {
        UniqueHashHashUnique {
            imp: self.imp.get_unique_constraint::<String>("hash"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UniqueHashHashUnique<'ctx> {
    /// Find the subscribed row whose `hash` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UniqueHash> {
        self.imp.find(col_val)
    }
}
